### ISSUE TITLE
videoディレクトリが存在しないのでローカルで実行できません...😇

### ISSUE THREAD

**Issue by hppRC** [huequica/soundrop_OtogibaraEra#17]
forkして動かして見たかったんですが, videoディレクトリがgitignoreされていて以下のエラーが出ちゃいました...😇

```
Module not found: Can't resolve './video/OtogibaraEra_Background.mp4' in '/path/to/repo/soundrop_OtogibaraEra/src'
```

仕様なら我慢します🔥
お手数ですがよろしくお願い致します😇

**Comment by huequica** [comment]
あ、それなんですけどファイルサイズが今8MBあって

+ ignore外して監視に入れちゃう
+ どっか別のストレージに入れて共有にする

のどっちかで考えてます
![スクリーンショット 2019-11-06 0 28 09](https://user-images.githubusercontent.com/40014236/68221257-83526e80-002c-11ea-81ce-61684ba25d78.png)

**Comment by huequica** [comment]
今決めました、動画入れます

**Comment by hppRC** [comment]
ありがとうございます！！

**Comment by huequica** [comment]
masterにMergeしたので`git pull origin master`してもらえれば完全に動くと思います
